export enum Permission {
  ASIGNAR_CONTRASEÑA_CEN = 'ESTABLECER_CONTRASEÑA_USUARIO_CEN',
  ASIGNAR_APLICACION_CEN = 'ESTABLECER_APP_USUARIO_CEN',
  ASIGNAR_ROL_CEN = 'ESTABLECER_ROL_USUARIO_CEN',
  REMOVER_ROL_USUARIO_CEN = 'REMOVER_ROL_USUARIO_CEN',

  CREAR_ROL_CEN = 'CREAR_ROL_CEN', 
  EDITAR_ROL_CEN = 'EDITAR_ROL_CEN',
  ASIGNAR_PERMISO_ROL_CEN = 'ESTABLECER_PERMISO_ROL_CEN',
  ELIMINAR_ROL_CEN = 'ELIMINAR_ROL_CEN',
  
  CREAR_PERMISO_CEN = 'CREAR_PERMISO_CEN',
  EDITAR_PERMISO_CEN = 'EDITAR_PERMISO_CEN',
  ELIMINAR_PERMISO_CEN = 'ELIMINAR_PERMISO_CEN',
 
  CREAR_APP_CEN = 'CREAR_APP_CEN',
  EDITAR_APP_CEN = 'EDITAR_APP_CEN',
  ELIMINAR_APP_CEN = 'ELIMINAR_APP_CEN',
  RESTABLECER_APP_CEN = 'RESTABLECER_APP_CEN',
}

